name: api-unit

on:
    push:
    pull_request:

jobs:
    unit:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [16]

        steps:
            - name: Checkout
              uses: actions/checkout@master
              with:
                  submodules: 'recursive'

            - name: Setup node env
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: ${{ matrix.node }}

            - name: wasm-pack-action
              uses: jetli/wasm-pack-action@v0.3.0

            - name: Install dependencies
              run: yarn

            - name: Run production build
              run: cd lumium-api && yarn build

            - name: Run unit tests
              run: cd lumium-api && yarn test
