name: space-e2e

on:
    push:
    pull_request:

jobs:
    e2e:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [16]

        steps:
            - name: Checkout
              uses: actions/checkout@master
              with:
                  submodules: 'recursive'

            - name: Setup node env
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: ${{ matrix.node }}

            - name: wasm-pack-action
              uses: jetli/wasm-pack-action@v0.3.0

            - name: Install dependencies
              run: npm run lumium-renderer:install --workspace lumium-space && npm install

            - name: Run production build
              run: cp lumium-space/.env.test lumium-space/.env && npm run build --workspace lumium-space

            - name: Run end-to-end tests
              run: npm run cypress:test --workspace lumium-space
